# GitHub Actions CI/CD Pipeline
# Bu dosya, otomatik dağıtım sürecini tanımlar

name: Deploy

# Tetikleyiciler
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# İşler
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build the Docker image first
      - name: Build Docker image
        run: |
          docker build -t nginx-docker-cicd:test .
          docker images

      # Run Snyk test
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: nginx-docker-cicd:test

      # If scan passes, push to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image
        run: |
          docker tag nginx-docker-cicd:test ${{ secrets.DOCKERHUB_USERNAME }}/nginx-docker-cicd:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-docker-cicd:latest

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here 