# GitHub Actions CI/CD Pipeline
# Bu dosya, otomatik dağıtım sürecini tanımlar

name: Deploy

# Tetikleyiciler
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# İşler
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run security scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-and-deploy:
    needs: [test, security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: cotneo/ops:latest

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here 